---
parameters:
  - name: defaultpipeline
    displayName: parameterspipeline
    type: string
    default: package
    values:
      - package
      - build
      - install
      - compile
      - deploy
      - clean
  - name: version
    displayName: javaversion
    type: string
    default: path
    values:
      - '1.8'
      - '1.11'
      - '1.17'
  - name: Directory
    displayName: javaDirectory
    type: string
    default: /usr/lib/jvm/java-17-openjdk-amd64
    values: 
      - /usr/lib/jvm/java-8-openjdk-amd64
      - /usr/lib/jvm/java-11-openjdk-amd64
      - /usr/lib/jvm/java-17-openjdk-amd64
  - name: mavenDirectory
    displayName: mavenDirectory
    type: string
    default: /opt/maven 
    values:
      - /opt/apache-maven-3.8.4/bin/mvn
      - /opt/maven
      - /opt/apache-maven-3.9.0/bin/mvn

stages:
  - stage: package
    displayName: buildingmavenpackage
    jobs:
      - job: packagejob
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: "${{ parameters.defaultpipeline }}"
              publishJUnitResults: yes
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: "${{ parameters.version }}"
              jdkDirectory: "${{ parameters.Directory }}" 
              mavenVersionOption: 'path'
              jdkDirectory: "${{ parameters.Directory }} " 
              mavenVersionOption: 'path'
              mavenDirectory: "${{ parameters.mavenDirectory }}"
        
          - script: aws s3 mb s3://springpetclinic22/    
          - script: aws s3 cp  '$(Build.Repository.LocalPath)/target/spring-petclinic-3.0.0-SNAPSHOT.jar' s3://springpetclinic22/ --acl public-read
       











